### ISSUE TITLE
Port from Amethyst Engine to Bevy

### ISSUE THREAD

**Issue by cdsupina** [thetawavegame/thetawave#2]
This issue will outline steps that need to be taken to port the game to Bevy. They will be listed and grouped in the order they should be done. You can find the Amethyst Engine code here: https://github.com/amethyst/theta-wave

- [x] Step 1
  - [x] Player Movement
  - [x] Debug Lines #9 
  - [x] Arena Borders #4 
  - [x] Game size/scaling #7 
  - [x] Background art #10  
  - [x] UI Placement
  - [x] Config and data files #7
  - [x] Pause game #22 
- [x] Step 2
  - [x] Formations #12 
  - [x] Player Health #16 
  - [x] Defense #17 
  - [x] Firing Blasts #15 
  - [x] Explosions (Projectiles and Mobs) #18 
- [ ] Step 3
  - [x] Consumables #21 
  - [ ] Items
  - [x] Barrel Roll Ability #28
  - [ ] Store
  - [x] Z Levels (Sprite Layering) #22 
- [x] Step 4
  - [x] Repeater boss #26 
- [ ] Finalize
  - [ ] Documentation Comments
  - [ ] Code Comments
  - [ ] Module Organization
  - [ ] Log Important Data

**Comment by cdsupina** [comment]
Good enough, may fork privately to to add items
